site_name: FastAPI Project Template
theme:
  name: material
nav:
  - Introduction: index.md
  - Tutorials:
    - Get Started: tutorials/get-started.md
  - How-to Guides:
    - Database: how-to/database.md
    - Documentation: how-to/documentation.md
    - Unit Test: how-to/test.md
plugins:
  search:
repo_name: quick-sort/fastapi-simple-template
repo_url: https://github.com/quick-sort/fastapi-simple-template
