"""Init Tables

Revision ID: 10ac93d61cdb
Revises: 
Create Date: 2024-11-03 00:13:36.350199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
#import pgvector
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm.session import Session
from app.db.models.user import UserRole, User
from app.utils.security import hash_password

# revision identifiers, used by Alembic.
revision: str = '10ac93d61cdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('active', 'deactive', name='userstate').create(op.get_bind())
    sa.Enum('admin', 'user', name='userrole').create(op.get_bind())
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('roles', sa.ARRAY(postgresql.ENUM('admin', 'user', name='userrole', create_type=False)), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('state', postgresql.ENUM('active', 'deactive', name='userstate', create_type=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
    session = Session(bind=op.get_bind())
    user = User(username='admin', email='admin@admin.com', password=hash_password('admin'), roles=[UserRole.admin])
    session.add(user)
    session.commit()

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    sa.Enum('admin', 'user', name='userrole').drop(op.get_bind())
    sa.Enum('active', 'deactive', name='userstate').drop(op.get_bind())
    # ### end Alembic commands ###
