"""Add User

Revision ID: 4703adcde28d
Revises: 
Create Date: 2024-10-20 20:28:12.569009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
#import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4703adcde28d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('admin', 'user', name='userrole').create(op.get_bind())
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'user', name='userrole', create_type=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    sa.Enum('admin', 'user', name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
